server:
  port: 8081
spring:
  datasource:
    username: root
    password: qjz19950920
    url: jdbc:mysql://localhost:3306/ruby?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qfedu.ruby.pojo