server:
  port: 8081
spring:
  datasource:
    username: root
    password: qjz19950920
    url: jdbc:mysql://10.8.155.66:3306/ruby?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    password: gaoyue159
    port: 25
    protocol: smtp
    username: 13949033311@163.com
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qfedu.ruby.pojo