server:
  port: 8081
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ruby?serverTimezone=GMT&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    default-encoding: utf-8
    host: smtp.163.com
    password: gaoyue159
    port: 25
    protocol: smtp
    username: 13949033311@163.com
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qfedu.ruby.pojo

